### ISSUE TITLE
Failed to automatically create the secret after setting up the SecretProviderClass with secretObjects.

### ISSUE THREAD

**Issue by lqdflying** [oracle/oci-secrets-store-csi-driver-provider#43]
`secrets-store-csi-driver.syncSecret` was enabled  as bellow:
```sh
$helm get values oci-provider -n vault
USER-SUPPLIED VALUES:
secrets-store-csi-driver:
  syncSecret:
    enabled: true
```
but once create the SPC through the description files as follows:
 ```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-demo
  namespace: vault  # Must match the Pod namespace
spec:
  provider: oci
  parameters:
    authType: instance
    vaultId: ocid1.vault.oc1.ap-singapore-1.gztsqqa***data masked***h7q
  secretObjects:
    - secretName: oci-secret-demo  # Kubernetes Secret Name
      type: Opaque
      data:
        - objectName: demo  # The OCI Vault Secret name
          key: demo  # The key inside the Kubernetes Secret
```
No secret was created, and upon checking the logs, there wasn’t a single error logged.
